name: Test Work Flows

on:
  workflow_dispatch:
  push:
    branches:
    - master
    - main
    
  
jobs:
  publish:
   name: publish
   runs-on: ubuntu-latest

   steps:
     - uses: actions/checkout@v3
     
     - name: Setup .NET
       uses: actions/setup-dotnet@v3
       with:
         dotnet-version: '7.0.x'

     - name: Restore
       run: dotnet restore ./GitHubActionSample.sln

     - name: Build
       run: dotnet build ./GitHubActionSample.sln

     - name: Test
       run: dotnet test ./GitHubActionSample.sln -c Release

     - name: Publish
       run: dotnet publish ./GitHubActionSample.sln --configuration Release --no-build